language: python
python:
  - 3.6

    # Write install command after writing requirements.md file
install: 
  - pip install -r requirements.txt
  - pip install codecov

script: 
  - pwd
  - coverage run Phase2_TripSage/tripsage/planner/functionaltesting.py


notifications:
  email:
    recipients: 
      - mvijaya2@ncsu.edu
      - nkashya@ncsu.edu
      - sbangal2@ncsu.edu
      - nrpandes@ncsu.edu
      - arames22@ncsu.edu
    
    on_success: never
    on_failure: always
    
after_success:
  - export CODECOV_TOKEN="4f39a2fc-3240-4cac-bd78-ac33c0336ebb"
  - bash <(curl -s https://codecov.io/bash)
