DirectionsResponse:
  geocoded_waypoint:
  - geocoder_status: OK
    place_id: ChIJ9-BRny9arIkRrfARilK2kGc
    type:
    - locality
    - political
  - geocoder_status: OK
    place_id: ChIJ8WYPEnHkrIkRfvJGionaeuE
    type:
    - locality
    - political
  route:
    bounds:
      northeast:
        lat: '35.9939234'
        lng: '-78.6380861'
      southwest:
        lat: '35.7795894'
        lng: '-78.9008909'
    copyrights: Map data ©2020
    leg:
      distance:
        text: 24.5 mi
        value: '39463'
      duration:
        text: 29 mins
        value: '1710'
      end_address: Durham, NC, USA
      end_location:
        lat: '35.9939234'
        lng: '-78.8987225'
      start_address: Raleigh, NC, USA
      start_location:
        lat: '35.7795894'
        lng: '-78.6381679'
      step:
      - distance:
          text: 0.1 mi
          value: '177'
        duration:
          text: 1 min
          value: '33'
        end_location:
          lat: '35.7811781'
          lng: '-78.6380861'
        html_instructions: Head <b>north</b> on <b>S Wilmington St</b> toward <b>New
          Bern Pl</b>
        polyline:
          points: mekyEp_~~MI?oCGqACI?s@CS?
        start_location:
          lat: '35.7795894'
          lng: '-78.6381679'
        travel_mode: DRIVING
      - distance:
          text: 0.2 mi
          value: '323'
        duration:
          text: 1 min
          value: '46'
        end_location:
          lat: '35.7812920'
          lng: '-78.6416689'
        html_instructions: Turn <b>left</b> onto <b>E Edenton St</b>
        maneuver: turn-left
        polyline:
          points: kokyE`_~~MCrD?NClACnBEjEAj@Aj@?d@
        start_location:
          lat: '35.7811781'
          lng: '-78.6380861'
        travel_mode: DRIVING
      - distance:
          text: 0.3 mi
          value: '436'
        duration:
          text: 1 min
          value: '40'
        end_location:
          lat: '35.7849294'
          lng: '-78.6423831'
        html_instructions: Turn <b>right</b> onto <b>N McDowell St</b>
        maneuver: turn-right
        polyline:
          points: apkyElu~~MmAC_AA_CEwBEoCG_@@G?G@GBA?E@GBGBEBEBIFILIHMXKTEHGLMPIJGF
        start_location:
          lat: '35.7812920'
          lng: '-78.6416689'
        travel_mode: DRIVING
      - distance:
          text: 0.6 mi
          value: '964'
        duration:
          text: 1 min
          value: '48'
        end_location:
          lat: '35.7934212'
          lng: '-78.6416819'
        html_instructions: <b>N McDowell St</b> turns slightly <b>right</b> and becomes
          <b>Capital Blvd</b>
        polyline:
          points: yflyEzy~~MIDEBEBGBI@GBG@UDYD_AN}AX}BZ[FG@K@M@K@oAB_BCIASAA?CAA?A?C?YCC?w@MiCQ_AIYESESEw@UoDs@qIcB{AS
        start_location:
          lat: '35.7849294'
          lng: '-78.6423831'
        travel_mode: DRIVING
      - distance:
          text: 0.3 mi
          value: '509'
        duration:
          text: 1 min
          value: '33'
        end_location:
          lat: '35.7968242'
          lng: '-78.6427331'
        html_instructions: Take the ramp to <b>Wade Ave</b>
        maneuver: ramp-right
        polyline:
          points: '{{myEnu~~MYSc@IQEKEOIGECAKKKMAAKMQYQWA?SUGEMGYMSIE?MCICKAA?O?Q?S@K@C?E@ODUJMFA@IFGFA?A@EFCBEDGFGJABIPINAFO\GPm@`BQ`@Qh@]~@GH'
        start_location:
          lat: '35.7934212'
          lng: '-78.6416819'
        travel_mode: DRIVING
      - distance:
          text: 0.1 mi
          value: '206'
        duration:
          text: 1 min
          value: '12'
        end_location:
          lat: '35.7977565'
          lng: '-78.6447126'
        html_instructions: Continue onto <b>Wade Ave</b>
        polyline:
          points: cqnyE`|~~MSd@Sj@{@~BYr@a@fA[|@
        start_location:
          lat: '35.7968242'
          lng: '-78.6427331'
        travel_mode: DRIVING
      - distance:
          text: 0.1 mi
          value: '176'
        duration:
          text: 1 min
          value: '10'
        end_location:
          lat: '35.7979218'
          lng: '-78.6466464'
        html_instructions: Slight <b>left</b> to stay on <b>Wade Ave</b>
        maneuver: turn-slight-left
        polyline:
          points: _wnyElh__NG^CTCTALAVAj@CtAAt@?@ARA^?b@
        start_location:
          lat: '35.7977565'
          lng: '-78.6447126'
        travel_mode: DRIVING
      - distance:
          text: 2.9 mi
          value: '4623'
        duration:
          text: 6 mins
          value: '339'
        end_location:
          lat: '35.8039107'
          lng: '-78.6943132'
        html_instructions: Continue straight to stay on <b>Wade Ave</b>
        maneuver: straight
        polyline:
          points: _xnyEpt__NBdABX@J@DDTBL@HFRDPHVBFDJLVLRJLDHJLR\JPLVHRJb@J\H^J^BFT~@\pA`@dBv@zCJf@Np@Pz@DVBLDd@?XAl@DREl@Ep@ALEt@Et@K~@Id@Ib@Mb@M`@OZOHA@?@KTMX]x@GJIJOPMJULYFM@G@[BODMDA@GDIFIHSVGDa@h@]`@o@v@MLgArAWZY`@MXOVEN?@A?ATGNENIVOp@YhAADo@lC?@ERQr@KHGTKd@Qp@I\CJMf@Id@AJAJCVCNDTAv@?R?x@@dE?nBAvE?z@Aj@?xA?j@Aj@?dC?j@?j@?j@?j@?~EAj@?vA?PAX?\ABCb@ARQx@AFS~@Mf@Mf@IXAJCH?BCXE^Ab@?RAbD?bA?f@A|@?l@?j@Af@?j@Aj@Al@AdA?hA@xA?j@?j@@j@?j@?l@@zE?xA?nA?x@ErD?dCC~E?xBId@EdAIrA?BGlAEl@Gd@In@Il@Gb@Mh@AHe@zBYnAI`@]~AKf@Kh@g@`CyAzGo@vCKd@CLAFQv@w@bDERCLQ|@CTQlAAFGj@Gd@Gr@
        start_location:
          lat: '35.7979218'
          lng: '-78.6466464'
        travel_mode: DRIVING
      - distance:
          text: 3.0 mi
          value: '4851'
        duration:
          text: 3 mins
          value: '169'
        end_location:
          lat: '35.8198645'
          lng: '-78.7420405'
        html_instructions: Keep <b>left</b> to continue on <b>Wade Avenue</b>, follow
          signs for <b>I-40 W</b>/<wbr/><b>RDU Intl Airport</b>/<wbr/><b>Durham</b>/<wbr/><b>Blue
          Ridge Rd</b>
        maneuver: keep-left
        polyline:
          points: m}oyEl~h_NGjAE~@AZ?r@ApA@j@?|ABtFBlF?hA@`B@bC?^@L?zE?`A?jBAbA?f@AfCCnBAbAA`A?TEpB?RAj@Aj@Cv@A^Ad@?BA`@?JGzB?HCj@AX?PE`AEnAA\A\Ex@Aj@ABErAEj@GxAGpAIrAO~AUnCUlCa@rDK~@Il@In@Kv@QpASlAQjAQ|@YjBEZYrA]dBa@dBa@dBCLq@fCg@jB_@lA}@rCe@vA[z@A@?@A@?@KV?@]~@Yv@o@bBa@~@_BtDMVAB_@x@]n@aAlBoA~BkAjBcA`BeAdByC~EmCrEiAjBSXW`@s@hAi@z@W`@i@z@s@hA{AfC_AvAw@lAsApBe@v@_BbCW`@i@z@}AfCsB`Di@x@CLGJ}@|AkAxBk@fAg@bACDk@jAQ^cAtBY~@
        start_location:
          lat: '35.8039107'
          lng: '-78.6943132'
        travel_mode: DRIVING
      - distance:
          text: 9.0 mi
          value: '14429'
        duration:
          text: 8 mins
          value: '463'
        end_location:
          lat: '35.8982166'
          lng: '-78.8673822'
        html_instructions: Merge onto <b>I-40 W</b>
        maneuver: merge
        polyline:
          points: casyEvhr_Ng@dAm@pAA@GNyBzE}@lBSb@}Nv[qKlU_BlDeBvD{B|EaDdHyGvNm@xAEJ_CnFkAhCa@|@IRq@|A]x@Ud@?@u@hBm@zAo@`BIT{@`CITc@lAQd@]dASn@Qd@Od@c@nAq@nBWr@M\Sb@cHtSQf@mApDaDnJ_AfCM^_@bAw@tBYp@_@~@y@tBWj@CBsCjGoE`K?@m@rAeAbC_@v@g@fAk@hAsH~P}GfOyFfMwAxCOVkBpD_A`BcAdBQX_A~AyDpGqBfDMPy@tAW`@uAzBuA|BCD_@n@GHiEfHuGtKuA|Bw@nAiAjBiK~PeG~JwA|Bu@lAmApBy@tAq@hAgE~GkEjHA?kEhHaBnCaBhCOXc@r@}FvJ}@vAoB|CqCrEqBbDmEhHS^yAbCg@x@wA~BwBpDGHcCrDwBtCk@v@eDdEyA|AyDbEaB~A_DvCc@^INQPMNo@l@iAfAWR{DtDeVrT_DvC{@t@o@l@eA`Am@h@YXu@p@u@r@_@\gAbAeA~@[X}@z@o@j@OL{@x@{@x@iAbAe@b@[Zw@r@m@h@}AxAa@^[XiCbCy@z@e@f@aAfA[`@A@]b@_@f@SVi@v@kAdBk@bAYd@Yf@_@l@c@~@e@~@{@jBg@jAs@hBk@~Ak@dBm@rBk@|Be@rBWrAUhAOz@EZKl@m@pE{BnP]bCEXs@fDMl@YfACLADGPK^K`@]fAy@fCGR]~@g@vAiApCIRQ`@KTYn@c@|@i@bAIP_AhBq@rAe@|@m@nA_@t@
        start_location:
          lat: '35.8198645'
          lng: '-78.7420405'
        travel_mode: DRIVING
      - distance:
          text: 7.3 mi
          value: '11820'
        duration:
          text: 7 mins
          value: '404'
        end_location:
          lat: '35.9877666'
          lng: '-78.8969958'
        html_instructions: Take exit <b>279B</b> to merge onto <b>NC-147 N</b> toward
          <b>Durham</b>/<wbr/><b>Downtown</b>
        maneuver: ramp-right
        polyline:
          points: '{jbzEbxj`NIHEBCBCDEFGLGJMRYj@e@`AWf@OTMTMRKPOTORMPQTMLQTMLQNSRYVSNMJ[RYPg@Xg@TYJg@P[Ha@L]FYDc@F_@Da@Bg@@_@@_AAe@CWCYC]C]GUEYGSE]Ka@MSK[Mc@QUM_@Sc@YUOSOQOQOOOMMAAUCsEuEmBgByAoAe@a@k@e@uAeAcAw@u@i@w@k@i@_@OKc@YSMQKu@e@e@Yi@Yo@Y]QwAq@aAe@kAg@kAe@mAc@eFaB{@WOE_@OeA[q@S{Bq@ME{Ac@aBe@_DaAgA[g@QaBe@{@Wm@SoA[aA]C?wBa@yAQcJiAaDa@e@GYCICQA{C_@{Dg@qGw@eAO{BYqEi@qFq@e@GC?eAMsBQ}@Iq@E}AIi@C[?s@C}BAiA?eA@uBDqAFs@Do@Ba@Di@D]BYDuAL{AR]FuB\iAReARIBo@No@NuDbAiA\c@PyAf@eA`@eAb@eAd@w@^iAj@y@b@iAl@mBhA}@d@WLaAb@aBr@A?_Bj@e@Nk@Ps@RkAZyA\c@Hk@Ju@LeBZc@JcCR_CJuBHwD@wDEi@CqEGgAAyA?m@?{ABcA?a@@m@B}BFwBLsDXsBPkCV_Ef@{Cd@uDh@i@FsCXcCPqCV]DuBXWHsA^SHuAh@gCvAuAz@gD`CeAt@YRoA|@cAt@A?ED}AjAaBhAcD~BcBlAq@f@m@b@QNA@sAlAqApAML_@b@c@f@QRc@j@i@t@q@|@Wl@oAfCKP[r@Sf@O^g@pACF]dAe@vAGPGVA?Op@eB`Gi@bBOf@CJy@pCQf@oAfEOf@]hAa@dAkBxGc@tAIX?@Wx@i@hBiAzD_@nAwAvEk@pBKZGRSt@IROj@aEfNYv@Up@GRe@rAIRCHSb@Q`@Q^S`@S^o@dAINCDEFGJaAjA_@b@_@\yB|BIHC@qBdBmBdBCFA@?@A?cB~Ao@l@m@l@k@p@ONY^Y^_@j@'
        start_location:
          lat: '35.8982166'
          lng: '-78.8673822'
        travel_mode: DRIVING
      - distance:
          text: 0.2 mi
          value: '280'
        duration:
          text: 1 min
          value: '15'
        end_location:
          lat: '35.9893082'
          lng: '-78.8994285'
        html_instructions: Take exit <b>12B</b> toward <b>Roxboro St</b>/<wbr/><b>Mangum
          St</b>/<wbr/><b>US-15 N</b>/<wbr/><b>US-501 N</b>
        maneuver: ramp-right
        polyline:
          points: qzszEfqp`NORA?CBEFY`@q@fA}@pA[f@EHILIPGJKVGNYv@a@jA
        start_location:
          lat: '35.9877666'
          lng: '-78.8969958'
        travel_mode: DRIVING
      - distance:
          text: 413 ft
          value: '126'
        duration:
          text: 1 min
          value: '12'
        end_location:
          lat: '35.9897461'
          lng: '-78.9007201'
        html_instructions: Merge onto <b>Jackie Robinson Dr</b>/<wbr/><b>N Service
          Rd E W</b>
        maneuver: merge
        polyline:
          points: edtzEl`q`Nq@tC[pAIX
        start_location:
          lat: '35.9893082'
          lng: '-78.8994285'
        travel_mode: DRIVING
      - distance:
          text: 184 ft
          value: '56'
        duration:
          text: 1 min
          value: '38'
        end_location:
          lat: '35.9901981'
          lng: '-78.9008780'
        html_instructions: Slight <b>right</b> toward <b>S Roxboro St</b>
        maneuver: turn-slight-right
        polyline:
          points: '}ftzEnhq`NGHCDEDA@A@EBG@G@E?G?I?UA'
        start_location:
          lat: '35.9897461'
          lng: '-78.9007201'
        travel_mode: DRIVING
      - distance:
          text: 0.3 mi
          value: '453'
        duration:
          text: 1 min
          value: '70'
        end_location:
          lat: '35.9937493'
          lng: '-78.8984186'
        html_instructions: Slight <b>right</b> onto <b>S Roxboro St</b>
        maneuver: turn-slight-right
        polyline:
          points: witzEniq`NkAq@eAi@g@YUOiC{Aq@_@OIgAm@YQSMCCUOA?AAECGG_@WiA_AECWS
        start_location:
          lat: '35.9901981'
          lng: '-78.9008780'
        travel_mode: DRIVING
      - distance:
          text: 112 ft
          value: '34'
        duration:
          text: 1 min
          value: '9'
        end_location:
          lat: '35.9939234'
          lng: '-78.8987225'
        html_instructions: Turn <b>left</b> onto <b>E Main St</b>
        maneuver: turn-left
        polyline:
          points: '}_uzEbzp`NITWd@'
        start_location:
          lat: '35.9937493'
          lng: '-78.8984186'
        travel_mode: DRIVING
    overview_polyline:
      points: mekyEp_~~MuFKgACCbEOtLApAmCEwFKoDEYD[Lc@b@g@fAW\QL]L_APwHlAm@FoAB_BC]CGA_@C{@MiE[m@KkA[aOwC{ASYSu@O[Oc@a@q@aAk@c@aA[g@Eu@By@Za@^W\e@fAyA~DmAzCsCxHQxAMdGBhBDd@Lr@ZdAl@dAp@fAVj@V`An@fCbCzJj@rCD~@Al@DRK~AGbAQtBShA[dAOZOHABYn@e@dAY\c@Xg@Hc@D]J]XyF~Gg@z@Uf@Kf@qBlIQr@KHo@jC]dBEb@@d@?jICnLAfNAtJG~ASlAUfAg@tBMfAC~GGlJ@fM@~LIrSOjBIvAMzBQtAa@dCgBlIyEzTqAvFk@nDYlCMjCAnABpMF|O@jIC~IQhNQtH[~IOnDOjDYrDk@|Gm@rFq@fFqAbI_BzH_CfJ_DtJO`@iCzGoCjG_B|C{CjFqLzRiItMoNxTqEhHm@fA}DjHiBtDcAtBY~@uAvCaEzIc_@vx@}Srd@_G~MgEzJcDtI}AnEyAjEiAbDa@`AeP~e@eD`JkCrGgJrS{DvI_JhSwOn]gBpDkDrGoIpNaL`Rm`Aj~Agt@plAkC|DcDlEeDdEyA|AyDbEaB~AcEvD[`@_DxC{h@jf@cLhKyJbJeHvG}DlEsAdBuB|CeAhBcCtEcBvD_BhEyAxEqApFcAtFsEr\y@`Eg@tBYdAkBdGyC|H{AdDeDrGsAlCi@~@STw@xA{AtCy@nA_AjAmAhAwA`AoAn@aA\uBd@mCR_B?}@GkBUmBg@iBy@mBmAaA}@WEaI}HaG}E{EmDyA_A{A_AyAs@cGqCyCiAaHyBgDeAyTwGiBk@qCy@{Ba@}L{AaFm@[Eug@mG{Fi@uESqDEoC@kHVcCTqD`@sCd@iEz@eFrAmBn@_DhAkChAeG|CkDnByAp@cBr@eCz@_Bd@eDx@kF~@c@JcCRuFToJC{FKkH@qGLkHf@_Gh@{IlA_Fp@wGj@oD\mCb@gBh@uAh@gCvA}F|DsF|DoPtLyDpDcBlBmA`Bq@|@Wl@{AxCo@zAyA~Du@`CaDvK_BlF_BnF_AnCyChK{HvWu@hC{E~O]dAgAtCkAbCcAbBiAvA_A`AcCfCuBfBsBpBcEzDoB`Cu@bAoCbEu@pAu@jBa@jAq@tCe@jBSVWHm@AoEeCkEeCsCcBwBcB]WITWd@
    summary: I-40 W and NC-147 N
  status: OK
